# Generated by Django 4.2.5 on 2023-09-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="projects",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AddField(
            model_name="projects",
            name="brief",
            field=models.TextField(default="this is brief for my projects"),
            preserve_default=False,
        ),
    ]
