# Generated by Django 4.2.5 on 2023-09-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_projects_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="image",
            field=models.ImageField(default="resume/default.jpg", upload_to="resume/"),
        ),
    ]
