# Generated by Django 4.2.5 on 2023-09-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0007_category_projects_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
