# Generated by Django 4.2.5 on 2023-09-20 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resume", "0008_delete_contact"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Projects",
            new_name="Project",
        ),
    ]
